"""adicionando nova tabela ordem

Revision ID: 05eb4a893e6a
Revises: dc48575e16ea
Create Date: 2024-11-01 22:44:18.361027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05eb4a893e6a'
down_revision = 'dc48575e16ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nameClient', sa.String(length=100), nullable=False),
    sa.Column('nameProduct', sa.String(length=100), nullable=False),
    sa.Column('numItems', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orders')
    # ### end Alembic commands ###
